name: Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      DAZE_PATH: .
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up V 0.2.4
      uses: nocturlab/setup-vlang-action@v1
      with:
        v-version: 0.2.4
        v_home: /opt/v
      id: v
    - name: Symlink V
      run: sudo /opt/hostedtoolcache/nocturlab/setup-vlang-action/0.2.4/x64/v symlink
    - name: Build Compiler
      run: sudo make

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up V version latest
      uses: nocturlab/setup-vlang-action@v1
      with:
        v-version: latest
      id: v
    - name: Build compiler
      run: v .

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up V version latest
      uses: nocturlab/setup-vlang-action@v1
      with:
        v-version: latest
      id: v
    - name: Build compiler
      run: v .