name: macos

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  run:
    name: Run
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up V version latest
      uses: nocturlab/setup-vlang-action@v1
      with:
        v-version: latest
      id: v
    - name: Build compiler
      run: v install pcre && v .